# Generated by Django 4.1.5 on 2024-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='images',
            field=models.ManyToManyField(null=True, to='field.fieldimages'),
        ),
    ]
