# Generated by Django 4.1.5 on 2024-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='local',
        ),
        migrations.AddField(
            model_name='field',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
