# Generated by Django 4.1.5 on 2024-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_field_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='field.fieldimages'),
        ),
    ]
